#!/bin/bash
ip addr add 50.3.8.3/24 dev eth0
ip addr add 100.2.3.3/24 dev eth1
ip addr add 100.3.5.3/24 dev eth2
ip link set eth0 up
ip link set eth1 up
ip link set eth2 up
ip addr add 3.3.3.3/32 dev lo
sysctl -w net.ipv4.ip_forward=1
/etc/init.d/frr start
