#!/bin/bash
ip addr add 50.7.1.1/24 dev eth0
ip addr add 100.1.2.1/24 dev eth1
ip addr add 100.1.4.1/24 dev eth2
ip link set eth0 up
ip link set eth1 up
ip link set eth2 up
ip addr add 2.2.2.2/32 dev lo
sysctl -w net.ipv4.ip_forward=1
/etc/init.d/frr start
